Garage2/Models/VehiclesDb.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Garage25.Models
{
    public class VehiclesDb : DbContext
    {
        public DbSet<vehicle> vehicles { get; set; }
    }
}

Garage2/Models/vehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Garage25.Models
{
    public class vehicle
    {
        public int Id { get; set; }
        [Required]
        [StringLength(7, MinimumLength = 6)]
        [RegularExpression(@"^[a-zA-Z]{3}\s\d{3}$",
            ErrorMessage = "Registreringsnummer ska följa ABC 123 med mellanslag!")]
        [Display(Name = "Registreringsnummer")]
        public string RegNumber { get; set; }
        [Display(Name = "Färg")]
        public string Colour { get; set; }
        [Display(Name = "Märke")]
        public Brand Brand { get; set; }
        [Display(Name = "Modell")]
        public string Model { get; set; }
        [Range(3,8 ,
            ErrorMessage = "Fordon med hjul färre än 3 eller mer än 8 är icke parkeringsbara!")]
        [Display(Name = "Antal hjul")]
        public int Wheels { get; set; }
        [Display(Name = "Parkeringstid")]
        public DateTime ParkedTime { get; set; }
       
    }
    public enum Brand
    {
        Volvo,
        Saab,
        Audi,
        BMW,
        Mazda,
        Nissan,
        Kia
    }
}

Garage2/Controllers/FindCarController.cs
using Garage25.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garage25.Controllers
{
    public class FindCarController : Controller
    {
        // GET: FindCar
        public ActionResult Index(string reg)
        {
            ViewData["reg"] = reg;
            VehiclesDb db = new VehiclesDb();
            var car = from c in db.vehicles  select c;
            if (!string.IsNullOrEmpty(reg))
            {
                car = car.Where(c => c.RegNumber.Contains(reg));
            }
            return View(car);
        }
    }
}

Garage2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Garage25.Models;

namespace Garage25.Controllers
{
    public class HomeController : Controller
    {
        VehiclesDb _db = new VehiclesDb();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        } 
    }
}

Garage2/Controllers/ReceiptController.cs
using Garage25.Models;
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garage25.Controllers
{
    public class ReceiptController : Controller
    {

        // GET: Receipt
        public ActionResult Compute()
        {

            vehicle car = (vehicle)TempData["Vehicle"];
            ViewData["reg"] = car.RegNumber;
            ViewData["brand"] = car.Brand;

            DateTime startTime = car.ParkedTime;
            DateTime endTime = DateTime.Now;
            TimeSpan diff = endTime - startTime;

            var minutes = diff.TotalMinutes;

            double hours = diff.TotalHours;
            int hour = (int)Math.Round(hours);
            ViewData["hour"] = diff.ToString(@"dd\.hh\:mm");
            int pricePerMinute = 1;


            int cost = (int)(pricePerMinute * minutes);
            ViewData["cost"] = cost;
            if (car == null)
            {
                return HttpNotFound();
            }

            return View();
        }
    }
}

Garage2/Controllers/vehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Garage25.Models;

namespace Garage25.Controllers
{
    public class vehiclesController : Controller
    {
        private VehiclesDb db = new VehiclesDb();

        // GET: vehicles
        public ActionResult Index()
        {
            return View(db.vehicles.ToList());
        }

        // GET: vehicles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vehicle vehicle = db.vehicles.Find(id);
            ViewData["id"] = id;
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // GET: vehicles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RegNumber,Colour,Brand,Model,Wheels")] vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                vehicle.ParkedTime = DateTime.Now;
                db.vehicles.Add(vehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vehicle);
        }

        // GET: vehicles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vehicle vehicle = db.vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,RegNumber,Colour,Brand,Model,Wheels,ParkedTime")] vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(vehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }

        // GET: vehicles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            vehicle vehicle = db.vehicles.Find(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            vehicle vehicle = db.vehicles.Find(id);
            db.vehicles.Remove(vehicle);
            db.SaveChanges();
            TempData["Vehicle"] = vehicle;
            return RedirectToAction("../Receipt/Compute");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Garage2/Views/FindCar/Index.cshtml
@model IEnumerable<Garage25.Models.vehicle>

@{
    ViewBag.Title = "Sök bil";
}

<h2>Sök bil</h2>
@using (Html.BeginForm("Index", "FindCar", FormMethod.Get))
{
    <div>
        <text>Skriv in registreringsnummer. </text><input type="text" name="reg" />&nbsp;
        <input type="submit" value="Sök" id="btnSubmit" />
    </div>
}

<div id="DivGrid">
    @{
        //tested by Mai .
        var reg = ViewData["reg"] as string; <!-- Typecasting is needed here -->

        if (Model.Count() > 0 && @reg != null)
        {
            var grid = new WebGrid(source: Model, canPage: true, rowsPerPage: 2, defaultSort: "Id");
            @grid.GetHtml(
                tableStyle: "PGrid", 
                headerStyle: "Header", 
                alternatingRowStyle: "altRow", 
                htmlAttributes: new { id = "DataTable" }, 
                columns: grid.Columns(
                    grid.Column("RegNumber", "Registreringsnummer"),
                    grid.Column("Brand", "Märke"),
                    grid.Column("ParkedTime", "Parkeringstid")));
        }
        else if (Model.Count() == 0 && @reg != null)
        {
            <hr />@Html.Label("Bilen finns inte i garaget !")<hr />
        }
        else if (Model.Count() > 0 && @reg == null)
        {
            <hr />@Html.Label("")<hr />
        }
    }
</div>

Garage2/Views/Home/About.cshtml
@{
    //ViewBag.Title = "About";
    ViewBag.Title = "Om oss";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

<p>Garage 2.0 startade 2012 av Nina, Mai, Per och Disa.</p>
<p>Det är ett toppmodernt, grönt garage med luftkonditionering och en kaffemaskin där du kan njuta av en kopp god kaffe helt utan kostnad. Vi har dessutom fräscha toaletter som du kan besöka.</p>

Garage2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title.</h2>
@*<h3>@ViewBag.Message</h3>*@

<address>
    Flemminggatan 102<br />
    112 45 Stockholm<br />
    <abbr title="Phone">P:</abbr>
    070 773 73 7
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">garagesupport@gmail.com</a><br />
    @*<strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>*@
</address>

Garage2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>*@

<div class="row">
    <div class="col-md-4">
        <h2>Vi erbjuder</h2>
        <p>
           När du parkerar hos oss hittar du ett säkert, välstädat, miljövänligtt garage som dessutom är kameraövervakat och bemannat dygnet runt. Vi har eluttag så att du kostnadsfritt kan tanka din elbil.
        </p>
        <p><a class="btn btn-default" href="../vehicles/Index">Lista parkerade bilar &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Priser</h2>
        <p>Hos oss kan du parkera per timme, en hel dag eller per vecka.</p>
        <p>Pris per timme: 60kr<br>
        Pris per dag: 250kr <br>
        Pris per vecka: 800kr</p>
         
        <p><a class="btn btn-default" href="../vehicles/Index">Lista parkerade bilar &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Tilläggstjänster</h2>
        <p>Vi erbjuder biltvätt medan du står perkerad hos oss.<br />
        Du kan dessutom byta vinter och sommar däck.</p>
        <p><a class="btn btn-default" href="../vehicles/Index">Lista parkerade bilar &raquo;</a></p>
    </div>
</div>

Garage2/Views/Receipt/Compute.cshtml
@model Garage25.Models.vehicle

@{
    ViewBag.Title = "Kvitto för parkerad tid";
}


<h2>Kvitto förparkerad tid</h2>

@using (Html.BeginForm("Compute", "Receipt", FormMethod.Get))
{
    <div>
        <text>ditt registreringsnummer : @ViewData["reg"]</text>&nbsp;
        
    </div>
}

<h3> Bilinformation </h3><hr />
<div>
    <b>Registreringsnummer:</b> @ViewData["reg"]<br />
    <b>Märke:</b> @ViewData["brand"]<br />
    <b>Totalparkeringstid:</b> @ViewData["hour"]<br />
    <b>Kostnad:</b> @ViewData["cost"]<br />
</div>

Garage2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
</head>


<body>
    
    <div class="main-header">Välkommen till Garage 2.0</div>
    @*<div class="hr1"</div>*@

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            
            <div class="navbar-header">
                
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Garage 2.0", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Hem", "Index", "Home")</li>
                    <li>@Html.ActionLink("Om oss", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Parkering", "Index", "Vehicles")</li>
                    <li>@Html.ActionLink("Sök", "Index", "FindCar")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content img-responsive" >
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - copyright Nina, Mai, Per, Disa</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Garage2/Views/vehicles/Create.cshtml
@model Garage25.Models.vehicle


@{
    ViewBag.Title = "Create";
}

<h2>Parkeringsdata</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bil</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNumber, "", new { @class = "text-danger" })


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Colour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Colour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.EnumDropDownListFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Brand, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand)
              
                @Html.ValidationMessageFor(model => model.Brand)
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })     
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Wheels, new { htmlAttributes = new { @class = "form-control", min = 3, max = 8 } })*@
                @Html.EditorFor(model => model.Wheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wheels, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ParkedTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParkedTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ParkedTime, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Parkera" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka till listan", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Garage2/Views/vehicles/Delete.cshtml
@model Garage25.Models.vehicle

@{
    ViewBag.Title = "Delete";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<h2>Hämta ut fordon</h2>

<h3>Är du säker på att detta är din bil?</h3>
<div>
    <h4>Bil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wheels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParkedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParkedTime)
        </dd>

    </dl>

    @*@using (Html.BeginForm()) {*@
       


    <div class="form-actions no-color">
        <input type="submit" value="Hämta ut" class="btn btn-default" />  |

        <!-- Field for your PRN Value -->
      
        <!-- Hidden field to store your ID (so that it will posted to your Edit Action) -->
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.ParkedTime)
        @*//<input type="submit" value="Hämta ut" class="btn btn-default"  />

            //@Html.ActionLink("Kvitto", "Compute", "Receipt", new { Id = Model.Id }, null)*@
        @Html.ActionLink("Tillbaka till listan", "Index")
    </div>
    
</div>
}

Garage2/Views/vehicles/Details.cshtml
@model Garage25.Models.vehicle

@{
    ViewBag.Title = "Details";
}

<h2>Detaljerade data</h2>

<div>
    <h4>Bil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colour)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colour)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wheels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParkedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParkedTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editera", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Tillbaka till listan", "Index")
</p>

Garage2/Views/vehicles/Edit.cshtml
@model Garage25.Models.vehicle

@{
    ViewBag.Title = "Edit";
}

<h2>Editera Data</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bil</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ParkedTime)

        <div class="form-group">
            @Html.LabelFor(model => model.RegNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Colour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Colour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Colour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wheels, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka till listan", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Garage2/Views/vehicles/Index.cshtml
@model IEnumerable<Garage25.Models.vehicle>

@{
    ViewBag.Title = "Index";
}

<h2>Lista på parkerade bilar</h2>

<p>
    @Html.ActionLink("Parkera din bil", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegNumber)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Colour)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wheels)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.ParkedTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegNumber)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Colour)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wheels)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.ParkedTime)
            </td>
            <td>
                @Html.ActionLink("Editera", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Detaljer", "Details", new { id=item.Id }) |
                @Html.ActionLink("Hämta ut", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

    </table>